### ISSUE TITLE
consider using Routes for routing

### ISSUE THREAD

**Issue by petri** [sanic-org/sanic#1318]
Routes https://routes.readthedocs.io/en/latest/ is a mature router implementation that focuses on URL routing and nothing more.

**Comment by vltr** [comment]
@petri @ahopkins tomorrow I'll probably have a good benchmark suite over some known (and lesser known) URL routers for Python :wink:

**Comment by vltr** [comment]
@petri I wrote a small benchmark suite for testing different routing systems in Python. Here's [the repository](https://github.com/vltr/very-stupid-simple-routers-bench). I don't believe Routes is a good choice and, if a mature routing system is to be considered, then I would really consider Falcon's.

**Comment by ahopkins** [comment]
@vltr nice work!

**Comment by sjsadowski** [comment]
I agree with @vltr but I will claim bias as I migrated to Sanic from Falcon.

**Comment by vltr** [comment]
@sjsadowski yeah, well, I'm glad this benchmark is just for the router :smile: 

Being "pure Python", the Falcon router really does a good job (Sanic does too, but with a lot of regex and high complexity searches, yet still error prone in some situations).

**Comment by ahopkins** [comment]
Since we are on the topic ...

I'm curious to hear how people would react to using C extensions or cython in situations like this one to gain some more performance.

**Comment by vltr** [comment]
@ahopkins not only performance may I add; the Sanic router, like I said, might be error prone in some situations exactly because of its complexity (and flexibility). I know very well that it was (made this way) with the best of intentions, but this might be a trade-off between having such flexibility on the router _or_ have a fast **and** reliable router ... It's hard to choose :sweat_smile:

**Comment by sjsadowski** [comment]
I tend to prefer flexibility over speed here (blasphemy?) because aside from everything else, we're still functioning at web-speed. I think also moving to an extension - that would be compiled - starts to increase difficulty of adoption for people who may not have access or support to build extensions.

**Comment by vltr** [comment]
No blasphemy at all. I believe that a compiled extension is on the table because we already depend on some (`httptools`, `multidict`). The point is the cost of having such flexibility on the router to be error prone and overly complex to maintain.

**Comment by ahopkins** [comment]
I was not proposing compilation for users of Sanic, but before the release (hence whoever it is that is going to work on the development of the router). We can pre-compile and just `import` as if it were written in Python.

**Comment by c-goosen** [comment]
> I agree with @vltr but I will claim bias as I migrated to Sanic from Falcon.

Not alone in that quest!

**Comment by skewty** [comment]
@ahopkins **uvloop** and **ujson** are already compiled dependencies.  The decision was already made to favor speed.  I say go for it.

**Comment by sjsadowski** [comment]
@ahopkins @vltr do we want to keep this open?

**Comment by vltr** [comment]
@sjsadowski yes, I think it's good to leave it open and start a further discussion in the community forum since our current Router (and overall Request workflow (see #1317 and related issues)) really needs some attention - either from the performance perspective to the complexity perspective, design and etc.

**Comment by ahopkins** [comment]
Related discussion here: https://community.sanicframework.org/t/making-sanic-even-faster/298?u=ahopkins

This is on my radar after ASGI.

**Comment by ahopkins** [comment]
Closing this. The forums have plenty more information about this.
