### ISSUE TITLE
Content-Type

### ISSUE THREAD

**Issue by Lagicrus** [sanic-org/sanic#1671]
**Origin Story**
I was testing my site via an online tester and it brought up the fact that my site did not specify the charset via the `Content-Type` header. Luckily I discovered after a quick bit of research that changing the `content_type` of the static file was added back in https://github.com/huge-success/sanic/pull/1267
As such I have currently added `content_type="text/html; charset=utf-8")` to my `app.static`'s so that it fixes that issue.
However, having to constantly keep adding that to all my static routes when I add more is not the best thing in the world.

**Solution**
Change the default content_type of `app.static` from `text/html` to `text/html; charset=utf-8`.
Which I believe is altering https://github.com/huge-success/sanic/blob/master/sanic/static.py#L111

**Comment by Tronic** [comment]
I just made a commit regarding this yesterday, changing the defaults of HTTPResponse and StreamingHTTPResponse to include charset. Looks like I missed one!

Another concern is that unknown types shouldn't be treated as `text/plain` but they should have either
- no content-type header [RFC-7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.5) -- making browsers sniff by content but then they get the charset wrong (ISO-8859-1 unless the format specifies otherwise e.g. by HTML meta charset element)
- `application/octet-stream`, making browsers download as file.

Nginx does the latter for files without extension or otherwise unrecognised, and it appears to work better in practice. Thus, HTTPResponse, StreamingHTTPResponse and static.py line 111 should probably default to `application/octet-stream`.

**Comment by Tronic** [comment]
Another consideration. Since the `content_type` argument is part of an easy API, and because the charset selection is Sanic internals, it might make sense to auto-append the charset whenever a text-like type is found:

```python
if 'content-type' not in headers and content_type:
    if 'charset=' not in content_type and (
        content_type.startswith('text/') or content_type == 'application/javascript'
    ):
        content_type += '; charset=utf-8'
    headers['content-type'] = content_type
```

What do you think, is this reasonable? Note that if specified via headers instead of the content_type argument, no such magic is applied.

**Comment by Lagicrus** [comment]
> I just made a commit regarding this yesterday, changing the defaults of HTTPResponse and StreamingHTTPResponse to include charset. Looks like I missed one!
> 
> Another concern is that unknown types shouldn't be treated as `text/plain` or `text/html` but they should have either
> 
> * no content-type header, as required by [RFC-7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.5) when type is not known -- making browsers sniff by content but then they get the charset wrong (ISO-8859-1 unless the format specifies otherwise e.g. by HTML meta charset element)
> * `application/octet-stream`, making browsers download as file.
> 
> Nginx does the latter for files without extension or otherwise unrecognised, and it appears to work better in practice. Thus, HTTPResponse, StreamingHTTPResponse and static.py line 111 should default to `application/octet-stream`.

I definitely agree with the StreamingHTTPResponse change. Sanic might be able to do something again `guess_type` like they have done already in https://github.com/huge-success/sanic/blob/master/sanic/static.py#L111
