### ISSUE TITLE
How to increase timeout on specific method?

### ISSUE THREAD

**Issue by ali-hallaji** [sanic-org/sanic#1824]
Is there any option to increase timeout and request size on the top of method such as decorators?
Sometimes we need to increase our time of request such as uploading files.
Also, I asked a question on [Stackoverflow](https://stackoverflow.com/questions/60915546/how-to-increase-timeout-while-uploading-on-the-sanic-framework) about this issue.

**Comment by Tronic** [comment]
An experimental branch PR #1791 already allows adjusting request max size in handlers and I could implement timeout adjustments on that as well. You can test the streaming branch by:

```
pip install git+https://github.com/Tronic/sanic@streaming
```

These features are expected to be available in Sanic 20.6 or later, once the streaming branch gets merged because without that it is difficult to implement such adjustments on per-route basis.

**Comment by ali-hallaji** [comment]
Thank you so much @Tronic 
But Is it a stable and reliable version? Because I need to use it from the community version(continuously updated by the community).
Also, I need to use such an option variable to set value for that on the top of the function.

**Comment by Tronic** [comment]
It works reliably but APIs are not finalised, so I would not recommend using it in any serious production setups at this time. By testing now you can affect how it is going to look, but otherwise you should wait until July or October for the first stable release.

Within this branch, if your route has `streaming=True`, large uploads should work without adjusting the limits manually. Streaming handlers get infinite request maximum size by default and the request timeout gets reset every time that any data is received from client.

**Comment by Tronic** [comment]
This still needs to be sorted out.
