### ISSUE TITLE
Deprecate StreamingHTTPResponse

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2002]
This should not happen in 21.3, but we should mark it for deprecation in 21.6, and remove it _after_ 21.12.

**Comment by endafarrell** [comment]
@ahopkins where can i read about this idea; and about what would replace it? 

We have a complex app built on Sanic and whether we return a HTTPResponse or a SreamingHTTPResponse depends on an incoming `Accept` header (all of our internal code is async generators, and for "non-streaming" responses we consume the generator and send back a single array of results).

We also make extensive use of type hints, so that one function is annotated as `-> Union[sanic.response.StreamingHTTPResponse, sanic.response.HTTPResponse]`

**Comment by ahopkins** [comment]
Thanks for sharing your use case. In the coming weeks I plan to fill out the new documentation with different use patterns and will make sure to include this. In brief, in 21.3 every response makes use of the internal streaming api. Therefore, there will not need to be a differentiation between the two types of response object types. I'll share a snippet of how to do this in the new environment when I'm back at my computer. But, as I mentioned we will not actually remove it for compatibility until further down the road.

**Comment by ahopkins** [comment]
You can read about the history and the PRs here:

https://community.sanicframework.org/t/new-streaming-api-and-other-major-changes/518
