### ISSUE TITLE
Request.stream read method arg

### ISSUE THREAD

**Issue by denisovkv** [sanic-org/sanic#2066]
**Is your feature request related to a problem? Please describe.**

Created this issue from [forum](https://community.sanicframework.org/t/specifying-bytes-quantity-in-request-stream-read/813) on @ahopkins advice.

In short, shouldn't `read` method of `request.stream` instance has `int` argument which allows user to specify how much bytes to read from stream?

**Describe the solution you'd like**

Something like https://docs.python.org/3/library/io.html#io.RawIOBase.read

Any thoughts?

**Comment by Tronic** [comment]
In general, with `stream.read` you get what the client sends, a single TCP packet or a few, to avoid extra buffering. When chunked encoding is used by the client, a chunk boundary also causes a fragment to be returned, even if some bytes of the next chunk were already received (and will be returned by the next `read` call).

For reference, Python's I/O APIs:
- `IOBase.read` should generally be implemented but is not specified because implementations vary
- `RawIOBase.read` reads an arbitrary number of bytes (just like Sanic's stream), up to a limit if given
- `BufferedIOBase.read` reads an exact number of bytes or up to EOF
- `BufferedIOBase.read1` is just like `RawIOBase.read`
- `asyncio.StreamReader` has `read` and `readexact` (alike `RawIOBase.read` and `BufferedIOBase.read`, respectively), and also implements `readline` and others.

Unfortunately the sync I/O APIs cannot be used in async code, and asyncio's `StreamReader` is not designed to be used outside of asyncio's own streams. Therefore, I don't see an API to be compatible with nor helper classes that could be used.

I would suggest implementing your own helper class with internal buffering if you need an exact number of bytes or readline in more than one handler (otherwise it is just a few lines of code to do that within the handler itself). Similarly, the received data may be fed to an incremental parser of MsgPack, JSON, XML etc. for immediate processing especially if the document is large, or if you need to receive a stream of such documents. Since the needs are diverse, this probably shouldn't be a part of Sanic core.
