### ISSUE TITLE
deprecate sanic.exceptions.abort?

### ISSUE THREAD

**Issue by artcg** [sanic-org/sanic#2068]
sanic currently offers a function called `abort` which just takes an integer, then raises an exception with the status code of that integer

If I was reviewing any code that used this function I would ask them to remove it, as it is instantly less readable than just raising the exception manually

There is two scenarios one might use the abort:

* you don't plan on catching the exception: in that case, better to use

`raise SanicException(status_code=400)  # example status code`

* you do plan on catching the exception: in that case, better to use the exact type of exception

`raise InvalidUsage()`

the code is then more grep-able as well as being more readable

Think about this scenario as an external user of a piece of code:

```
def some_route():
  abort(402)
  return sanic.response.text('hello')  # does this run? I have to check sanic documentation to know...
```

```
def some_route():
  raise SanicException(status_code=402)
  return sanic.response.text('hello')  # I know 100% that this will never run
```

Personally, I would therefore deprecate the sanic.exceptions.abort function, will open the topic for discussion here

**Comment by ashleysommer** [comment]
Hi @artcg 
When Sanic was first released back in 2017, one of the design goals was to be as similar as possible to Flask, to reduce the learning curve, so that users coming from Flask would be able to use their existing experience, and even reuse a lot of Flask code.

In Flask standard and documented way to quickly and easily throw an exception back to the HTTP client is to use `abort()` with an integer argument.
We had a few Issues and PRs opened early on in Sanic to add an identical `abort()` feature (eg, see #739 and #740). So thats a bit of background for _why_ its there.

But I agree with your argument in general. It seems like a pretty bad code smell when I see it in use, and personally I don't use `abort()` in any of my Sanic applications. However if we deprecate it, I fear it will break the user experience for quite a lot of Sanic users (especially those still migrating from Flask).

**Comment by artcg** [comment]
Well that is a pretty reasonable explanation,

why flask introduced it then, I don't know, but can understand the desire for compatibility with their syntax... will leave this open a day or two in case anybody else feels like commenting but would otherwise close this issue

**Comment by ashleysommer** [comment]
Sanic is going through a significant growth and maturation phase right now. With the implementation of the new streaming backend, and the new ast-based router, we've removed and replaced some big chunks of "old Sanic", with some breaking changes falling in with this upcoming 21.3 release. So now is probably a good time to think about deprecating Flask-like features like `abort()`.

**Comment by ahopkins** [comment]
I am in favor of deprecating it. This means adding a `UserWarning` in 21.6, and removing it in 21.12.

As @ashleysommer stated, the original project was more of a proof of concept to make Flask-like async framework. I think we have grown much beyond that and while it is helpful to keep in mind to "ease the transition", this is something that good documentation can take care of.

Please feel free @artcg to submit a PR. Again, we can leave it open for more conversation for a couple weeks to see if anyone is adamantly opposed to this. However, I would rank the project's goals of performance, flexibility, and clean coding above Flask-parity.
