### ISSUE TITLE
ModuleNotFoundError: No module named 'sanic_testing'

### ISSUE THREAD

**Issue by atezerjani** [sanic-org/sanic#2086]
**Describe the bug**
An exception happen in unittesting the sanic rest server with this backtrace:

It's happening in version 21.x.x and not in 20.x.x

**Code snippet**
self = Sanic(name="test.unit.rest.apitestcase")

    @property
    def test_client(self):  # noqa
        if self._test_client:
            return self._test_client
        elif self._test_manager:
            return self._test_manager.test_client
>       from sanic_testing.testing import SanicTestClient  # type: ignore
E       ModuleNotFoundError: No module named 'sanic_testing'

.tox/py37/lib/python3.7/site-packages/sanic/app.py:794: ModuleNotFoundError

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [MacOs, Debian 10]
 - Version [21.3.x]

**Additional context**

**Comment by ashleysommer** [comment]
Hi @atezerjani 
Testing in sanic v21.3+ requires installation of python package sanic-testing in your test environment.
(It's not installed as a Sanic dependency because it's not used in regular operation of the application).
You can install all test-dependencies of Sanic by using the "extras" syntax, eg:
```
pip3 install --upgrade sanic[test]
```
