### ISSUE TITLE
`Config.load_environment_vars` doesn't appear to filter out lowercase configuration keys

### ISSUE THREAD

**Issue by Varriount** [sanic-org/sanic#2120]
Currently, `Config.load_environment_vars` doesn't filter out lowercase configuration keys - its only criteria is that the configuration key matches the prefix. This differs from the other configuration loading methods, `from_envvar` and `from_pyfile`, which filter out configuration keys with any lowercase letters.

**Comment by ahopkins** [comment]
I am assuming you are looking at an old version as `from_pyfile` and `from_envvar` are deprecated and removed.

Regardless, presumably prefixed env variables would take a little more intentional effort to set so I am not that worried about it.

If you would like, please make a PR to add `k.isupper()` to `load_environment_vars`. If you do, please also make sure that we catch prefixed and _not_ uppercase and throw a deprecation warning stating the breaking change will be removed in 21.12.
