### ISSUE TITLE
Request streaming (upload to server) where upload is to large sometime fails to return PayloadTooLarge to client

### ISSUE THREAD

**Issue by ingarpedersen** [sanic-org/sanic#2131]
By setting request.stream.request_max_size to the maximum supported size I expected that the client should receive a 413 (PayloadTooLarge) response if the upload stream is larger than request_max_size. This works in some cases in other cases not.

```

@pytest.fixture
def app():
    app = Sanic("test app")
    return app

def test_streaming_new_api_payload_size(app):
    @app.post("/1", stream=True)
    async def handler(request):
        request.stream.request_max_size = 100
        async for data in request.stream:   # correctly throws 413 on large payload
            assert data
            assert isinstance(data, bytes)
        return text("OK")

    request, response = app.test_client.post("/1", data="TEST data")
    assert response.status == 200 # always works

    request, response = app.test_client.post("/1", data="TEST data"*100)
    assert response.status == 413 # always works

    # the post below randomly throws a ValueError exception instead of receving a 413 response
    request, response = app.test_client.post("/1", data="TEST data"*100000)
    assert response.status == 413

```

As long as data size of upload is less than one chunk it seems to work every time. But for larger uploads the client will sometime raise a value exception:
ValueError('Request and response object expected, got ([<Request: POST /1>, None])')
An unrelated change in the code may get the code working again (until the next change), so it would appear this problem is timing related.

Versions:
Linux: Ubuntu 20.04 LTS
Python: 3.8.5
sanic: 21.3.4
sanic-routing: 0.6.2

**Comment by Tronic** [comment]
The ValueError comes from sanic-testing and it indicates that no response was received by the test client.

A HTTP server cannot properly reject a request when there is a large body attached. It would need to receive the entire thing, and to avoid doing so, Sanic immediately emits the 413 response and then closes the socket.

Better clients such as curl should be able to read the 413 response asynchronously while still sending the body. Browsers cannot do it asynchronously but it kind of works unless the request is in hundreds of megs because very large send buffers are used so the browser simply scrams the entire request into its buffers and then reads the response without blocking. The test client doesn't buffer and cannot read any response until it has flushed the request down the pipes (into Sanic's small receive buffer).

The random behaviour that you are seeing is probably because of subtle timing differences between the test client managing to read the response prior to failing of broken pipe. I would suggest not testing 413 with this toolkit because it simply doesn't work too well.

**Comment by Tronic** [comment]
Some clients might also use the `expect: 100-continue` mechanism where the client waits for server approval prior to sending a large request body, and Sanic can reject it cleanly. Unfortunately most clients don't use that and in any case it only works with content-length request header (not when size is not known in advance).

**Comment by ozancaglayan** [comment]
Hi,

On a slightly related topic, when streaming is enabled, the size limit seems to be lifted in `sanic/app.py`

`request.stream.request_max_size = float("inf")`

but actually `content-length` for the request header is properly set to the final size of the file upload. Is there a reason why you are not sticking to the requested limit? Is it because the streamer may not know the size in advance as well? But maybe in cases where a binary file is getting streamed (this is the case in my example), allowing to keep the size limit intact would help?

Right now, streaming handler receives the request although the non-streaming one directly rejects it without receiving the body.

**Comment by ahopkins** [comment]
That's probably it. Can you open as a new discussion and link back here. IIRC we just blindly lift the limit when streaming expecting the handler to deal with it. When there's an express size, perhaps we can still respect that but would need some investigation. On the surface it sounds reasonable though. I'd just want to avoid having to do additional unnecessary checks for the majority of use cases where I imagine it might not be explicit. And, as I said, the general idea is the dev will have to self-handle.

**Comment by ahopkins** [comment]
This issue has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/streaming-handling-improvements/1192/1

**Comment by Tronic** [comment]
On that related note, the max size limit is secondary. Sanic does stick to what the content-length header says and will receive exactly that much even if the limit is inf.

The main issue is probably caused by the difficulty of rejecting a large request. For some amount of data above your limit Sanic simply discards the incoming data until it can respond. If it is much too large, Sanic has no other option than to close the TCP connection. I think it still attempts to write a PayloadTooLarge response first but depending on client and transfer buffers that may or may not be received at all. Your 900 kB payload might hit the area in between where it sometimes goes through and otherwise doesn't.
