### ISSUE TITLE
Maximum request header size capped at 8k

### ISSUE THREAD

**Issue by moorglade** [sanic-org/sanic#2153]
**Describe the bug**
Sending a request with a large header to a Sanic server results in 413 (Payload Too Large) response. 

This happens regardless of the `request_max_size` setting.

If I undserstand the implementation correctly, the maximum HTTP header size is hardcoded to be 8k:

https://github.com/sanic-org/sanic/blob/main/sanic/http.py#L172

**Expected behavior**
I think maximum header size should be configurable and values > 8k should be allowed.

**Environment (please complete the following information):**
 - OS: CentOS 7
 - Version 21.3.4

**Comment by Tronic** [comment]
The limit is in place to mitigate DoS attacks which may easily consume all server memory and crash the entire system (or at least Sanic processes, if the admin was careful to set suitable ulimits). If you need larger headers, you are probably doing something very wrong, and as a primary solution you should be looking into fixing your application (e.g. use a session token instead of scramming everything into cookies). The header memory use expands a lot as Sanic parses the byte buffer into Python data structures, and with a large number of parallel requests this becomes a problem. Other software such as proxies and clients may also have their own limits that affect for your application at some point.

That being said, it might still be a good idea to have it configurable for those special cases where huge headers cannot be avoided, especially in intranet services where DoS is not a concern. I believe this needs to stay at least a few kilobytes lower than `REQUEST_BUFFER_SIZE` (by default 64 KiB) to avoid deadlocks.

Relevant discussion elsewhere:
https://stackoverflow.com/questions/686217/maximum-on-http-header-values
https://github.com/nodejs/node/issues/24692

**Comment by moorglade** [comment]
Thanks for clarification. I believe there was no such limit in 20.12 and I was a bit surprised when I saw all those 413 errors after upgrading to 21.03. I agree that reducing the header size is the best approach and this is what I will try to do, although I believe this can sometimes be problematic, e.g. when integrating with an existing service which uses large headers.

**Comment by ahopkins** [comment]
I am okay allowing for some variance here, and in most cases am on board with letting the developer make the choice. However, I'd feel more comfortable having a max config value to guard from someone putting too high a value. It's Python, so someone that really knew the consequences and had the use case, they could still monkey patch around it. I believe some other servers out there do something similar. A default value that can be configured up to some maximum.

**Comment by aaugustin** [comment]
FWIW I've been using the approach of "design it so users who really want to change it can monkey-patch it" to tackle this request and it went well — no issues filed anymore — https://websockets.readthedocs.io/en/stable/security.html#other-limits

**Comment by ahopkins** [comment]
Added a quick PR that moves the constant to the `Http` class to make it easier to monkeypatch if desired.

**Comment by Tronic** [comment]
I did a quick test with Chrome: it will happily send at least about 12 kB single `Cookie` header line (didn't test larger), if there are enough cookies, but a single cookie cannot be larger than 4 kB. Because this is a single line, many HTTP servers give 413 errors even if they otherwise allow for the header to be larger but impose a line length limit (unless that too is configurable).

Suggesting `config.REQUEST_MAX_HEADER_SIZE` setting for this (total header size, Sanic doesn't have line length limit), to complement the existing `REQUEST_MAX_SIZE` and `REQUEST_BUFFER_SIZE` settings.

**Comment by ahopkins** [comment]
@Tronic Let's continue this conversation in #2155.
