### ISSUE TITLE
``FALLBACK_ERROR_FORMAT`` cannot be set even when the ``update_config`` function is called because the ``ErrorHandler`` object receives the default value of the config and is initialized.

### ISSUE THREAD

**Issue by SaidBySolo** [sanic-org/sanic#2276]
**Describe the bug**

https://github.com/sanic-org/sanic/blob/3262878ebd41aa2230ef15d4475bbcf223b2356b/sanic/app.py#L139-L184

Referring to the code above, since the config is set when the Sanic object is initialized, you cannot pass a fallback value to the ErrorHandler even if you set ``config.update_config`` or ``app.config.FALLBACK_ERROR_FORMAT = "json"``.

To solve this, you can pass the config argument when initializing the Sanic app, but this doesn't seem to be intended.

**Code snippet**
```py
app = Sanic(__name__)

@app.main_process_start
async def start(app, loop):
    app.config.FALLBACK_ERROR_FORMAT = "json"
```

**Expected behavior**
Even if you use ``config.update_config`` or ``app.config.FALLBACK_ERROR_FORMAT = "json"``, the error handler should normally receive this value.

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Version [21.9.1]

**Additional context**

I wanted to open a PR on this issue, but I'm not sure where to touch.

**Comment by prryplatypus** [comment]
Seems to have been introduced in #2162

**Comment by prryplatypus** [comment]
@ahopkins, how would you like to fix this one? I guess the simplest way would be to just do this, but that could lead to inconsistent behaviour depending on the initialisation config value (which is what's causing this issue in the first place). https://github.com/sanic-org/sanic/blob/392a4973663631d011bd147a97347fb442d5a532/sanic/errorpages.py#L386-L394

```diff
    if not renderer:
        # Make sure we have something set
        renderer = base
        render_format = fallback

        if request:
+           render_format = request.app.config.FALLBACK_ERROR_FORMAT
            # If there is a request, try and get the format
            # from the route
            if request.route:
```

**Comment by ahopkins** [comment]
Yeah, there is a very delicate balance in that function to finding the right format. I am not sure that I would want to add that layer there. It really should be set on the error_handler object like in your suggestion.

TBH,  we really need to be hikacking the setter. Which, admittedly is something we do only some of the time. This can lead to inconsistencies and is something we should probably address.

I think the best solution is to catch this in the setter (whether as an object or a dict) and to update the value on the error handler as in your suggestion above. I would also suggest that if the error handler is not already the default value, then maybe we throw a warning that it is being overridden. You might be able to see where this slippery slope is going. The question then is what happens if the error handler was specifically set to the value that happens to be the default? In that case, maybe it needs to default to a sentinel value then be updated at startup in the finalization.

---

So, after all that, I think the way to handle it is like this:

1. Take the initialization time injection out:

```diff
--- a/sanic/app.py
+++ b/sanic/app.py
@@ -195,9 +195,7 @@ class Sanic(BaseSanic, metaclass=TouchUpMeta):
         self.configure_logging: bool = configure_logging
         self.ctx: Any = ctx or SimpleNamespace()
         self.debug = False
-        self.error_handler: ErrorHandler = error_handler or ErrorHandler(
-            fallback=self.config.FALLBACK_ERROR_FORMAT,
-        )
+        self.error_handler: ErrorHandler = error_handler or ErrorHandler()
```

2. Instead, add it here:

```diff
@@ -1627,7 +1625,9 @@ class Sanic(BaseSanic, metaclass=TouchUpMeta):
     async def _startup(self):
         self.signalize()
         self.finalize()
-        ErrorHandler.finalize(self.error_handler)
+        ErrorHandler.finalize(
+            self.error_handler, fallback=self.config.FALLBACK_ERROR_FORMAT
+        )
```

3. Set the default to our `_default` sentinel. Then in `ErrorHandler.finalize` we can check if the value was changed (in which case we can throw up a warning or error). 

This method should be backwards compat.
