### ISSUE TITLE
multiprocessing error when runs on macos big sur

### ISSUE THREAD

**Issue by zillionare** [sanic-org/sanic#2312]
**Describe the bug**

when sanic starts with multiple session, it crashes as :

```
objc[96314]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[96315]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[96314]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[96315]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Code snippet**
    app.run(
        host="0.0.0.0",
        port=port,
        workers=sessions,
        register_sys_signals=True,
        protocol=WebSocketProtocol,
    )

**Expected behavior**
No exception, no crash

**Environment (please complete the following information):**
 - OS: macos big sur, apple m1
 - Version 

https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr

**Comment by ahopkins** [comment]
I admittedly only took about 30s to look at that SO thread. It seems like the suggestions is to use `spawn` over `fork`, which we cannot do. If this is an OS limitation, then it unfortunately means that we may have another OS on which we cannot support multiple workers since we rely upon `multiprocessing`.

**Comment by ahopkins** [comment]
To tack on to this... adding support to run in `spawn` mode is something I have explored, and is something that has been talked about a lot. It is of course potentially a pretty big breaking change that we need to monitor the impacts from closely. However, I do suspect this is something we will finally try to achieve in 2022. But, it is highly OS specific because of how different OS handle multiprocessing and also port binding.

**Comment by Tronic** [comment]
Really need to reimplement the server startup so that it can work without forking. IIRC, it involves two main milestones:
- Restructure things so that you can start new processes that then know that they are workers (not sure if mp-spawn is the way to go here)
- In the master convert the socket fds for passing to worker processes and then somehow send them over. This is of course done completely differently on Windows vs. other OS. But the Python standard library offers those functions.

**Comment by Tronic** [comment]
If that can be implemented, I don't think we need fork at all anymore. Any performance advantages of forking vs. separate processes are miniscule because we only run a few processes anyway.

**Comment by ahopkins** [comment]
It is possible. I've gotten it running like this. But, the problem (as you said) is making sure all the right env is set. I actually do not think this is as big a challenge as it had been. But definitely a post-LTS project.

**Comment by Tronic** [comment]
REUSEPORT/REUSEADDR absolutely cannot be used for this. On Mac only one process will then receive all requests and the other only acts as fallback, and I believe while it is different on other platforms (these flags are evil), it is not going to be any better.

**Comment by ahopkins** [comment]
> On Mac only one process will then receive all requests

Are you sure about that? Being Darwin/BSD, I would be surprised to learn that is the case.

**Comment by Tronic** [comment]
I tried it a couple of years back, specifically to fix this problem in Sanic. Found out that this was the case and then looked it up on Stackoverflow or somewhere that others had noticed the same.
