### ISSUE TITLE
RFC: Multi-application serve

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2348]
## Background

Running multiple applications has been possible in Sanic for a long time. It does, however, take a pretty decent understanding of the operation of the Sanic server to do it properly. Things to consider include:

- loop management
- listener execution
- startup time optimizations
- multi-worker and auto-reload multiprocessing
- cross-platform support issues (looking at you Windows)

Over the course of the last six months in particular, I have seen a noticeable rise in the number of support queries where people are trying to do this. Whether it is to have a HTTP >> HTTPS proxy, web server plus chatbot, or serve multiple routes on different host/port configurations, the point is that there is a definite rise in the number of people looking to run multiple Sanic applications side-by-side.

With the efforts we have taken to make sure that multiple applications can co-exist, it seems only natural that we provide a first-class API for running them.

## Proposed solution

We create a _new_ high-level API that can easily handle this.

First, we create a method with an **identical** signature to `app.run`. Its job is to do everything that `app.run` would do, cache the `server_settings` for later usage, and stop at the point where it starts the loop.

```python
app1 = Sanic("ApplicationOne")
app2 = Sanic("ApplicationTwo")

app1.prepare(port=7777)
app2.prepare(unix="/path/to/sock")
```

Second, there is a single class method that runs the loop and executes the server(s).

```python
Sanic.serve()
```

The first application defined in the application registry becomes the "primary." That application is run normally as would otherwise happen with `app.run`. Any other applications in the registry that have been "prepared" will be setup using `create_server` such that all of their lifecycle events are properly run.

**Comment by vltr** [comment]
> With the efforts we have taken to make sure that multiple applications can co-exist, it seems only natural that we provide a first-class API for running them.

I agree with that. I'm not sure if we need to tackle it directly inside Sanic or if that could become a different project. We need to discuss a bit more about that.

> The first application defined in the application registry becomes the "primary." That application is run normally as would otherwise happen with `app.run`. Any other applications in the registry that have been "prepared" will be setup using `create_server` such that all of their lifecycle events are properly run.

I like that, since this need generally comes after "something else" already running (in our case, most likely a Sanic instance). I think this could prevent us from falling into the pitfall of trying to write some sort of "app server", which (IMO) we should walk far away from (as intent, not dismay, to get myself clear from the start) :sweat_smile: 

# Other thoughts

As a "runner", I think it might be a good idea. As something to deal with a "multi-worker environment", hmmmm, I really don't know, for some reasons:

- I think we're past the idea that we should try to control resources (such as processes) as "resource limited solutions" since there's already so many different recipes and solutions out there (from `supervisord` to a container). We can try to make our alternate solution, but I think that's way better as a snippet ...
- I would really like to reiterate that there's so many different solutions out there already that's it's hard to say "use this" - I was a big fan of multi-worker before you (@ahopkins) made my mind to use multiple single-process instances behind a load-balancer, so ...
- I'm not trying to say we shouldn't care about resources (they've always been finite) as I believe we should use them as they're available.

> Auto-reload multiprocessing

(and)

> cross-platform support issues (looking at you Windows)

Oh boy ... Where to get started ?! I think [we need to get back to 2018](https://community.sanicframework.org/t/following-auto-reload-support-for-windows/35) as I even got some stuff partially working :grimacing:

**Comment by ahopkins** [comment]
I am not suggesting that we solve resource management or that we even come close to supervisor-like functionality. This is meant purely as a method to bind multiple applications to differing socket tuples.

Besides the convenience this makes in doing HTTP redirection, livereload.js server, or something similar, I really would like to get something like this included for the HTTP/3 branch I am working on. This would be an ideal scenario for something like this.

**Comment by vltr** [comment]
> This is meant purely as a method to bind multiple applications to differing socket tuples.

ahhhhh!!! ok then ... that actually makes sense in my head now :sweat_smile: 

> This would be an ideal scenario for something like this.

agreed.

**Comment by Tronic** [comment]
Supposedly this also allows serving `::1` and `127.0.0.1` from a single instance on all OSes, as well as TLS redirect and `.well-known` over HTTP when the main server is HTTPS. If all that, this is the second best news that I have heard in ages (the best one being that Sanic HTTP/3 is being worked on too).

**Comment by ahopkins** [comment]
@Tronic 

```python
from sanic import Request, Sanic, json

app = Sanic("one")


@app.get("/")
async def handler(request: Request):
    return json({"foo": 1})


app.prepare(host="127.0.0.1", debug=True)
app.prepare(host="::1")
Sanic.serve()
```

![image](https://user-images.githubusercontent.com/166269/148202608-61e8e48e-bfcd-41d5-bc1d-6531ab4f98e3.png)

**Comment by ahopkins** [comment]
I am hoping to get #2347 finalized and merged in the next week or so. There are enough structural changes to how applications are started that it would be worth it to get this in before progressing too much further with HTTP/3. It would be great if we could get the initial HTTP/3 support out in March.
