### ISSUE TITLE
State Update Across All The Workers by a Single HTTP Request

### ISSUE THREAD

**Issue by elina-israyelyan** [sanic-org/sanic#2365]
I'm trying to update the states across all my workers by making a single HTTP request to one worker. When I make a single call I only update the state of the worker that received the request and am not able to update the others'.

It would be better if there is an argument for Sanic().run() function which will enable streaming a state across the workers, a possibility to give a global variable as an argument and make it the same(streamed) across all workers. 
The only solution I can find is [here](https://medium.com/@sandeepvaday/route-triggered-state-update-across-python-sanic-workers-a0f7ab0f6e4) and I think a feature mentioned above will make it easier and nicer to code.

**Comment by ahopkins** [comment]
Hello @elina-israyelyan 

This is not a feature that we will introduce to the core project. The problem is that it requires a very opinionated and application specific set of decisions to be made. For example, is an application be run on a single box, or distributed throughout a cluster? How should the synchronization be performed?

A shared-state across applications runs is the domain of databases. I have tackled this problem personally in a variety of ways, and it really depends upon the problem at hand.

- I have [used a pubsub](https://gist.github.com/ahopkins/5b6d380560d8e9d49e25281ff964ed81)
- Stored data in a DB using push event to store in the application
- Stored data in a DB and used a [task](https://sanic.dev/en/guide/basics/tasks.html) to poll the DB

Sometimes you really do not need the item to be in memory, in which case a simple DB read works wonders. This is especially true of a key/value store using Redis, or something equivalent.

I also would like to mention that @ashleysommer just released a new package that builds off the Redis concept I just mentioned and sticks it on your `app.ctx` with minimal setup:

https://github.com/ashleysommer/sanic-synchro-ctx

This might be exactly what you are looking for.

---

I hope this helps. Let us know if you have any questions, but I would suggest one of the above options as your way forward.

**Comment by elina-israyelyan** [comment]
@ahopkins Thanks a lot ! I will try the suggested solutions and let me revert with questions if any !

**Comment by elina-israyelyan** [comment]
I solved it with the sanic-synchro-ctx package where I shared the data I needed across all the workers. Thank you !

**Comment by ahopkins** [comment]
Thanks for sharing.
