### ISSUE TITLE
Sanic raising 503 before timeout period exhausted

### ISSUE THREAD

**Issue by Charles-Hello** [sanic-org/sanic#2424]
8|sanicgame  | 2022-04-06T09:46:43: [2022-04-06 09:46:43 +0000] - (sanic.access)[INFO][192.168.1.50:62892]: POST http://192.168.1.145:8888/robot/wx  503 730
<img width="478" alt="image" src="https://user-images.githubusercontent.com/73318286/161948244-73c83edc-2dee-4487-8004-8166b96a64dc.png">

**Comment by Charles-Hello** [comment]
I don't know, after setting these, it will still report the same error

**Comment by Charles-Hello** [comment]
sanic  22.3.0

**Comment by prryplatypus** [comment]
How are you making this request? Using cURL or similar? Can you post the command you're using and a small code snippet that this can be reproduced with?

**Comment by Charles-Hello** [comment]
@prryplatypus 
<img width="844" alt="image" src="https://user-images.githubusercontent.com/73318286/162564876-6d8bcdae-472c-4938-a24d-8f3a79702d99.png">
I just traverse the list and send requests to other servers

<img width="609" alt="image" src="https://user-images.githubusercontent.com/73318286/162564946-e13696a9-4efa-451e-b2d8-615971eeb482.png">

**Comment by Charles-Hello** [comment]
When I stay in the task for too long, sanic will automatically explode 503 730 errors

**Comment by Charles-Hello** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/73318286/162566906-ccf117c6-f381-4f38-a0ba-77690842e560.png">
What is the specific reason? ? Is it my bad asynchronous writing or is it a problem with sanic?

**Comment by Charles-Hello** [comment]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/73318286/162566959-dcaa6cae-7f03-4fa1-8024-cfd24b88b4ca.png">
<img width="485" alt="image" src="https://user-images.githubusercontent.com/73318286/162566972-bd3c19b0-925d-47c7-ae02-af88feb9ba00.png">

**Comment by Charles-Hello** [comment]
I have set the value of RESPONSE_TIMEOUT to 60 according to the error report, but the server will still stop the task. When my await asyncio.sleep(30), the sanic server will not even execute the function below, and the terminal will explode 503 directly. , the error of 730

**Comment by Charles-Hello** [comment]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/73318286/162567083-e559c925-dea3-4eab-b0eb-e7280e0a0f33.png">
Just like this, after five or six seconds, the server will not automatically explode 503 and 730 errors

**Comment by prryplatypus** [comment]
A couple of things I can notice:

1. Try using [`aiohttp`](https://docs.aiohttp.org/en/stable/) or [`httpx`](https://www.python-httpx.org/) instead of `requests` if you can. `requests` is blocking, and it makes async pretty much useless 😉. 
2. Opening files is also a blocking operation. Instead of doing `with open(...)` on each request, you might want to load the files once during application startup, save it to `app.ctx` and then read it from there by using `request.app.ctx`. Note that this will only work if the file's contents is static/doesn't change.
3. You can run the app by simply doing `app.run(...)`. No need to do `asyncio.run(...)`.
4. If sending those requests takes some time, you might want to make use of [signals](https://sanic.dev/en/guide/advanced/signals.html#adding-a-signal), so that you can respond to the request but keep that task running in the background.

As to why the request is timing out before the amount of time you configure, I am unsure why that could be happening. Maybe one of the other devs can help us out.

In the meantime, would you give those steps above a try and let us know if they work?

Best,
@prryplatypus.

**Comment by Charles-Hello** [comment]
解决了。不过我把异步换成了不异步就解决了。不过这样看起来挺怪的

**Comment by prryplatypus** [comment]
Glad to hear! I’ll leave this open so @ahopkins can clarify on the 503 when he’s around :)

**Comment by ahopkins** [comment]
Is this an issue? Closing. If there is an issue please open and provide me with some copy/pastable code to replicate.
