### ISSUE TITLE
Manually triggered auto-reload

### ISSUE THREAD

**Issue by zikphil** [sanic-org/sanic#2429]
Hello fantastic community,

I am using vault and consul to dynamically configure my sanic application. I am trying to find a way to make it so everytime the vault secret is updated remotely, it kicks a reload of the sanic application. Very similar to what the autoreload feature is doing today.

I have a process running in another thread that loops through and makes sure that when credentials/secret expires, it reloads. I would like to be able to call a function to make the server reload, is that something that exists today?

Phil

**Comment by prryplatypus** [comment]
Does Vault/Consul store configurations in files or in-memory? If it stores them in the filesystem, you could always add a directory to watch for changes manually, as indicated in the [user guide](https://sanic.dev/en/guide/deployment/development.html#automatic-reloader).

Otherwise, I don't believe there's currently a way to manually trigger a reload (maybe someone else can prove me wrong), so I'll mark this issue as a feature request :)

**Comment by ahopkins** [comment]
That is correct. There is not currently a method to do this manually. It does not sound like it would be a terribly difficult feature to add, and would be a reasonable addition. As mentioned, currently the only way that this happens is by looking for changes in the filesystem.

1. It looks for changes in loaded Python files that existed at the time of startup
2. It looks for changes in files in the `reload_dir`

**Comment by zikphil** [comment]
Hey guys,

Yes that's here is what I ended up doing:

- Added `.something-something` to the `reload_dir`
- Registered a task to continuously scan for the latest Vault secret versions
- If the upstream version changes, I change a timestamp in the `.something-something/__init__.py` to trigger a reload.

**Comment by prryplatypus** [comment]
That works! Gonna keep this issue open though, since -as Adam said- it’s a reasonable thing to add :)
