### ISSUE TITLE
Allow WorkersManager.THRESHOLD adjustment

### ISSUE THREAD

**Issue by notzippy** [sanic-org/sanic#2629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

During startup, my app functioned fine on my machine. Failed to start on a colleague with the following error
```
 [ERROR] Not all workers are ack. Shutting down.
 [ERROR] Experienced exception while trying to serve
```
Tracing this down to the [THRESHOLD](https://github.com/sanic-org/sanic/blob/main/sanic/worker/manager.py#L23) value which is a kill-all action. The threshold value which at last release was 50, but I see is now set to 300 is not configurable, and it should be IMO. 

I modified my app startup to do
```
    from sanic.worker  import manager
    manager.WorkerManager.THRESHOLD = 500
```
Obviously, this is a very fragile solution at best

### Describe the solution you'd like

Have the Threshold value configurable. I see in #2610 that someone already modified the value from 50 to 300. But in this scenario, a more configurable solution would make sense.

**Comment by ahopkins** [comment]
That pattern of monkey patch is the way to handle. There are some other low level values like that so that it's possible to change without really being a config value and overloading the namespace. In v22.12 it will be highly unlikely to need to touch it since exceptions on startup will kill the main process immediately without needing the deadlock check. 30s should be plenty except when it's not and we'll have documentation to that effect and an error pointing devs to it. The solution will be the exact snippet you provided above. Closing this as its no longer an issue on main and will not be on released version in another week or so.
