### ISSUE TITLE
how to use response.stream in v23.6 or Or a new similar feature

### ISSUE THREAD

**Issue by Dr-lau** [sanic-org/sanic#2800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

i want use     return response.stream(
        camera.stream,
        content_type='multipart/x-mixed-replace; boundary=frame'
    )
in my project, but in v23.6 this api has been removed , i do not know how to implement similar functions.
Can you help me?

### Describe the solution you'd like

how to use response.stream in v23.6 or similar feature

**Comment by Tronic** [comment]
Streaming the response the new way as in https://sanic.dev/en/guide/advanced/streaming.html#response-streaming

Something along these lines, adapt to your use case:
```python
@app.route("/")
async def stream(request):
    response = await request.respond(content_type="multipart/x-mixed-replace; boundary=frame")
    async for frame in camera.stream:
        await response.send(frame)
```

**Comment by Dr-lau** [comment]
thanks,

**Comment by peilongchencc** [comment]
@Tronic 

Hello, I would like to fetch **user's historical chat data** through the `post` method and then pass this chat data to a large language model's API.

The large language model returns content via streaming output. I will then process the results returned by the large language model and subsequently stream out the processed results.

My code structure is as follows:

```python
from sanic import Sanic
from sanic import response

app = Sanic("my_app")

@app.route("/ans", methods=["POST"])
async def answer(request):
    # fetch user's historical chat data.
    chat_history = request.form.get("chat_history")

    url = "https://xxx/sse/paas4Json/..."
    header = {
        'Accept': 'text/event-stream'
    }
    # Invoke the API of a large language model.
    response = requests.post(url=url, data=chat_history, stream=True, headers=header)
    response.raise_for_status()

    # Parse the streaming output results of a large language model.
    for line in response.iter_lines():
        line = line.decode('utf-8')
        if line and line != '' and line.startswith('data:'):
            data_content_dict = json.loads(line)
            value = json.loads(data_content_dict["data"][0]["value"])
            rtn = value["MessageBody"]["DirectMessageBody"]["SentenceList"][0]["Content"]
            # I would like to return `rtn` in a streaming manner.
            yield rtn

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8848)
```

I would like to return `rtn` in a streaming manner. I referred to the code on your website (https://gist.github.com/ahopkins/9cdf98147da863a0c1c5b0b8581d6980), but due to my limited understanding of web communications, I'm not sure how to use the `Response streaming` technique within the `post` method. 

Could you help me with an example of a `post` method that uses `Response streaming`?

I hope to get your assistance with this.

Ps: My Sanic version is 23.12.1.
