### ISSUE TITLE
 sanic integrates gRPC

### ISSUE THREAD

**Issue by mpv945** [sanic-org/sanic#2842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The spring boot project is restructured, and the plan is to use python plus gRPC microservice architecture. Can gRPC processing be started when sanic is started?

### Describe the solution you'd like

After starting port 8000, you can start another gRPC service port for gRPC service processing.

**Comment by sjsadowski** [comment]
Hi. Sanic doesn't do gRPC natively and is not part of our plan at this time.

**Comment by Tronic** [comment]
They are completely incompatible, and need to run on different ports. You can use a HTTP proxy like Caddy to join both services together on your public HTTPS server on the same domain on port 443, as Caddy will serve it using all HTTP versions and thus is also compatible with gRPC (that typically uses HTTP/2, not at all supported on Sanic because we skipped over to H3).
