### ISSUE TITLE
Trusted proxies

### ISSUE THREAD

**Issue by Commandcracker** [sanic-org/sanic#2902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

`FORWARDED_SECRET` can only be used with the `Forwarded` header. There sould be another way to verify proxies.

### Describe the solution you'd like

A proxy can be verified by checking the request ip against a list of trusted proxies.

**Comment by Tronic** [comment]
We have not planned for this feature, as its security is dubious at best and the standard Forwarded header provides a secure alternative. For typical installs, you can attain reasonable security simply with `PROXIES_COUNT=1` using the legacy headers, optionally adding the real IP header name your proxy sends (just make sure to firewall your service to prevent direct connections to it that bypass the proxy).

**Comment by Tronic** [comment]
To expand that a bit, you would typically need to open up CIDRs (address spaces) of a proxy provider, or otherwise have configuration to add multiple IPs and IPv6 as trusted proxies. Setting such configuration in a single string becomes cumbersome and checking them at runtime against every request takes time. In this sort of setup the real vulnerability is exposing your backend to Internet without firewall, and the trusted proxy IP setting cannot protect from that.

Presumably you are using something like Cloudflare to prevent DDoS to your service, but if your backend is directly exposed, the adversary can simply bypass the proxy and DDoS your backend directly. You don't need to check the incoming address (for a trusted proxy) if the backend is not exposed to any hostile network (i.e. it only listens to localhost or is otherwise firewalled to only accept connections from the trusted proxy).

Still, I suppose that PRs on this are welcome, if you feel the feature really is necessary.
