### ISSUE TITLE
mypy error type for async get function in HTTPMethodView

### ISSUE THREAD

**Issue by FirePanda169** [sanic-org/sanic#2916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Mypy throws an error overriding the signature of the get method, as it is described only for synchronous execution.

```
error: Signature of "get" incompatible with supertype "HTTPMethodView"  [override]
note:      Superclass:
note:          Callable[..., Any] | None
note:      Subclass:
note:          def get(self, request: Request[Any, Any]) -> Coroutine[Any, Any, HTTPResponse]
```

I suggest changing the description of the get method /sanic/views.py to:

```
get: Union[Callable[..., Any], Coroutine[..., Any], None]
```

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

Linux

### Sanic Version

23.12.0

**Comment by ahopkins** [comment]
PR welcome :wink:

**Comment by decarv** [comment]
That did not solve the problem for me. `mypy` still complains and I have no idea why.

It works if `None` is removed from the type definition.

```python
 get: Union[Callable[..., Any], Coroutine[..., Any]]
```

I cannot explain this behavior.

**Comment by swtnk** [comment]
@ahopkins 
The problem is here when we are using mypy and try to implement get method
https://github.com/sanic-org/sanic/blob/da1c6465852c8fc0b77ee2618d845665292045e0/sanic/views.py#L118

It should not have `Optional` as implemented here:
https://github.com/sanic-org/sanic/blob/da1c6465852c8fc0b77ee2618d845665292045e0/sanic/views.py#L147-L158

If there is no handler defined then server is having Attribute error anyways.
Example:
```log
AttributeError: type object 'MyView' has no attribute 'get'
```

Proposed solution:

\- `get: Optional[Callable[..., Any]]`
\+`get: Callable[..., Any]`

* Kindly suggest better solution or if there is a way to implement get in class based view if we are using mypy.

**Comment by ChihweiLHBird** [comment]
I am going to work on this if nobody else started it
