### ISSUE TITLE
Need an option to generate a skeleton project for app

### ISSUE THREAD

**Issue by r0075h3ll** [sanic-org/sanic#3006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Need a clearly documented basic skeleton project structure for a sanic application.

### Describe the solution you'd like

Reference: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website

### Additional context

Need a command line option to generate something like [this](https://github.com/hiraqdev/base-sanic).

**Comment by Tronic** [comment]
The difference to Django is that Sanic is so much simpler it doesn't really need any more than one Python file:
https://sanic.dev/en/guide/getting-started.html#getting-started

For a larger application, Blueprints will useful to keep it structured:
https://sanic.dev/en/guide/getting-started.html#getting-started

I don't think any of this can be meaningfully generated because each app has different needs and Sanic tries to avoid needing any boilerplate code and config files (that could be generated).

**Comment by r0075h3ll** [comment]
Blueprints do really help to introduce structure to the app.

However, a skeleton project structure with a set of pre-configured centralized server config files, etc. would help avoid boilerplate code. Just a suggestion.

**Comment by ahopkins** [comment]
We had this conversation recently on the Discord server. There's no single way to build, and part of Sanic's core is to remain unopinionated. However, at the urging and suggestion of users, I am working on some docs that will suggest patterns for development. I am not sure about building those into the library itself with a self-scaffolding CLI.
