### ISSUE TITLE
app.static with default route to index.html

### ISSUE THREAD

**Issue by albanm** [sanic-org/sanic#893]
I think autoindex is usually the name of this option for a web server. I wish to serve a directory using app.static and the index.html file should be served at the root of the directory.

I don't see an option for this in sanic.

**Comment by albanm** [comment]
Using app.static 2 times works : 

    app.static('/public', './public/index.html')
    app.static('/public', './public')

So this issue is not critical at all. But I still believe that it is an expected functionality when serving static directories.

**Comment by r0fls** [comment]
I think autoindex is actually when it produces a directory listing _if_ there is no index.html. Is that what you're asking for, or just that the index.html is exposed via `app.static` as the root route?

**Comment by albanm** [comment]
For my use case I was mostly interested in the second half, but yes the 2 things are usually associated.

I am not stuck in any way by this, I just think it is handy and somewhat expected of a web server and therefore might be added to the backlog. For example the static middleware of the express framework has this functionality by default.

**Comment by sjsadowski** [comment]
I think this issue is a bit stale, but I don't know that based on the use cases I've seen previously with Sanic this is something that would be a high value target. Gonna mark it as a feature request and see what the general interest in adopting it is.

**Comment by vltr** [comment]
My personal opinion is that Sanic is a framework for developing API centric, web _dynamic_ content. There are a lot of well tested, stable servers that can handle static files (like nginx) and also provide a proxy for your Sanic application. Regarding my use cases, I don't even know why there is a static handler at all.

**Comment by Juanlu001** [comment]
I was about to open a new issue for this: trying the sample code from https://github.com/huge-success/sanic/issues/374#issuecomment-276552506 raises an `IsDirectoryError`.

**Comment by sjsadowski** [comment]
@Juanlu001 Can you open the new issue? Throwing an error is a different problem than the one here.

**Comment by ahopkins** [comment]
Seems stale and a feature with low interest. If there is a renewed discussion, perhaps take it to the community forums. Closing for now.

**Comment by vvaradarajan** [comment]
My use case is a web-app that is a client-server. The client is a javascript app (web-components node-modules ), and the server is the Sanic-python web-Server app. As usual the client runs in the web-browser and communicates to server via url's. It is straight-forward to run this as two applications. However both are deployed on the same server, and I wish to serve the client to the browser using the server app with a static rout. I am able to do this using the app.static directory pointing to the directory of the javascript app. This works fine except that I have put in the 'index.html' at the end. It would be nice to default to index.html if no file is specified. (Note: I use the app.static to server a directory, so that relative references in the index.html and other associated javascript files resolve properly). I will try the nginx method suggested, and that may work - thanks

**Comment by ahopkins** [comment]
@vvaradarajan can you open this as a new issue for discussion and just reference this one?

**Comment by Tronic** [comment]
I don't see @vvaradarajan mention continuing the discussion elsewhere but I am reopening, as I find myself implementing the "workaround" pattern in most of my apps now. The currently working form of it is

```python
app.static('/', 'static/')
app.static('/', 'static/index.html', name='index')
```

I am suggesting that a single `app.static` call should do both. The newly added change requiring routes to have unique names made the workaround a bit more difficult, as a separate name needs to be provided for it.

Whether "index.html" would be looked for in each subdirectory as well, or only at the static root is of lesser importance to me. Simply something like the following would be satisfactory for me:

```python
app.static('/', 'static/', root="index.html")  # URL / returns static/index.html instead of giving an error
```

**Comment by ahopkins** [comment]
I did some playing around with something like this earlier this year. If enabled, and no index, then it would spit out an nginx like file browser. I never committed the code though. I'll find the branch and push it and we can discuss there.

**Comment by ahopkins** [comment]
Please open as new issue.

**Comment by Tronic** [comment]
> I did some playing around with something like this earlier this year. If enabled, and no index, then it would spit out an nginx like file browser. I never committed the code though. I'll find the branch and push it and we can discuss there.

Shouldn't do that by default either, because it would conflict with another route on site root, ditto with serving index.html, it needs to be an option not enabled by default. I won't open another issue for now but hopefully a suitable simplification for these typical patterns is found (e.g. automatic naming of routes differently or something else).

**Comment by ahopkins** [comment]
Yes, opt in.
